nodeLinker: node-modules

enableGlobalCache: true

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-babel-release-tool.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-babel-release-tool/main/bundles/%40yarnpkg/plugin-babel-release-tool.js"
releaseTool:
  ignoreChanges:
    - "*.md"
    - "*.txt"
    - test/**
    - "**/test/**"
    - codemods/**
    - "@(!(native-modules|built-ins|plugins|package)).json"
yarnPath: .yarn/releases/yarn-berry.cjs
