name: Set npm Registry Latest Tag

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of package'
        default: 'holocron'
        required: true
        type: choice
        options:
        - '@americanexpress/one-app-runner'
        - '@americanexpress/one-app-locale-bundler'
        - '@americanexpress/one-app-dev-bundler'
        - '@americanexpress/one-app-bundler'
        - '@americanexpress/eslint-plugin-one-app'
      version:
        description: 'version to tag'
        required: true
        type: string
      tag:
        description: 'tag'
        default: 'latest'
        required: true
        type: choice
        options:
        - latest
        - alpha
        - beta
jobs:
  set-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: npm dist-tag add ${{ github.event.inputs.name }}@${{ github.event.inputs.version}} ${{ github.event.inputs.tag }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}