name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.x', '12.x', '14.x' ]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Install
        with:
          node-version: ${{ matrix.node }}
        uses: actions/setup-node@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install
        run: yarn install
      - name: Unit Tests
        run: yarn test:unit
      - name: Git History Test
        run: yarn test:git-history
      - name: Lockfile Lint Test
        run: yarn test:lockfile
      - name: Lint
        run: yarn test:lint
