name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18.x' ]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git remote set-branches --add origin main
          git fetch
      - name: Node Install
        with:
          node-version: ${{ matrix.node }}
        uses: actions/setup-node@v1
      - name: Installing Packages
        env:
          NODE_ENV: development
        run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test:unit
      - name: Git History Test
        run: yarn test:git-history
      - name: Lockfile Lint Test
        run: yarn test:lockfile
      - name: Lint
        run: yarn test:lint
